// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tramcan2.models;

namespace tramcan2.Migrations
{
    [DbContext(typeof(CanDbcontext))]
    [Migration("20230405020128_themghichu")]
    partial class themghichu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("tramcan2.models.NhomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("TenNhom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NhomUser");
                });

            modelBuilder.Entity("tramcan2.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Ma")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("tramcan2.models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BienSoCuoiXe")
                        .HasColumnType("text");

                    b.Property<string>("BienSoDauXe")
                        .HasColumnType("text");

                    b.Property<int>("CMNDXe")
                        .HasColumnType("integer");

                    b.Property<int>("DTXe")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChuXe")
                        .HasColumnType("text");

                    b.Property<int>("MaTheXe")
                        .HasColumnType("integer");

                    b.Property<double>("TrongTai")
                        .HasColumnType("double precision");

                    b.Property<string>("XeChiCan1Lan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
